{% set name = "sphinxcontrib-websupport" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0b7367d3bac6454b1f97e42aa8c4d4d4a1b756d525fc726ebbe5571e033e79cd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - flit-core >=3.7
  run:
    - python
    - jinja2
    - sphinx >=5
    - sphinxcontrib-serializinghtml

test:
  source_files:
    - tests
  imports:
    - sphinxcontrib
    - sphinxcontrib.serializinghtml
    - sphinxcontrib.websupport
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://pypi.org/pypi/sphinxcontrib-websupport
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENCE.rst
  summary: Sphinx API for Web Apps
  description: |
    sphinxcontrib-websupport provides a Python API to easily integrate
    Sphinx documentation into your Web application
  doc_url: https://www.sphinx-doc.org
  dev_url: https://github.com/sphinx-doc/sphinxcontrib-websupport

extra:
  recipe-maintainers:
    - chohner